// <auto-generated />
using Mango.Servicies.ProductAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Servicies.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContests))]
    [Migration("20230918160620_SeedProduct")]
    partial class SeedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Servicies.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Ladno",
                            ImageUrl = "https://www.gamberorossointernational.com/wp-content/uploads/2022/11/samosas.jpg",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Ok",
                            ImageUrl = "https://i.pinimg.com/originals/ba/e6/81/bae681e42f19849474d825e5a0ca6f3f.jpg",
                            Name = "Paneer Tikka",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Norm",
                            ImageUrl = "https://i.pinimg.com/originals/70/cd/54/70cd5435c438141df65542d33340f98e.jpg",
                            Name = "Sweet pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Snacks",
                            Description = "lll",
                            ImageUrl = "https://storage.myseldon.com/news-pict-e7/E762CB007B23468FE0B8D7FD994EEEE2",
                            Name = "Shaurma",
                            Price = 5.5
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Alcochool",
                            Description = "Privet From Russia",
                            ImageUrl = "https://fikiwiki.com/uploads/posts/2022-02/1645022844_34-fikiwiki-com-p-kartinki-vodka-36.jpg",
                            Name = "Vodka",
                            Price = 1.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
